### ISSUE TITLE
G-mode does not activate at startup

### ISSUE THREAD

**Issue by londresarthur** [T-Troll/alienfx-tools#142] opened 2022-06-08 21:19 UTC
**Is your feature request related to a problem? Please describe.**
G-mode is not saved to apply at startup, so you have to apply it every time you turn on your computer

**Describe the solution you'd like**
It would be interesting if the G-mode was applied automatically at startup, as it is done in the fan curve.

**Describe alternatives you've considered**
I didn't think of anything.

**Additional context**
![image](https://user-images.githubusercontent.com/104213042/172719082-714f57f9-5492-4624-aab7-14fe7eb3fcc0.png) (Before restart)

![image](https://user-images.githubusercontent.com/104213042/172719184-096932b2-77ae-48e3-91ae-4c5fb96a6bf1.png) (After restart)

**Comment by T-Troll** [comment] 2022-06-08 22:49
Duplicate of #123

**Closed by T-Troll** 2022-06-08 22:49 UTC
Labels: duplicate
