### ISSUE TITLE
All Lights Not Working On Key Board Since 9.0.2

### ISSUE THREAD

**Issue by JazzyJazzjazzy** [T-Troll/alienfx-tools#467] opened 2024-10-14 13:48 UTC
I have an Alienware m18 and since updating to 9.0.2, when I turn it on, some keys from the keyboard don’t have their lights on. The keys are F1, F12, mute (mic and audio) and windows right.

**Comment by T-Troll** [comment] 2024-10-22 07:57
It's a duplicate of #462

**Closed by T-Troll** 2024-10-22 07:57 UTC
