### ISSUE TITLE
Installation Folder

### ISSUE THREAD

**Issue by TheSQLGuru** [T-Troll/alienfx-tools#239] opened 2022-11-13 22:21 UTC
When installing via the .msi file, the installation folder is set as C:\Program Files\AlienFX Tools\

IMPROVEMENT: Check for an existing installation, and if found use the existing installed folder as the installation folder. In my case, the folder would be set as D:\Program Files\Utilities\AlienFXTools\

Also, if an installation is found, change the action from "Installing AlienFX Tools" to "Upgrading AlienFX Tools".

**Comment by T-Troll** [comment] 2022-11-14 00:21
Duplicate of #184.

Being honest, all installer APIs are quite stupid or not free. I check them all, upgrade and update capabilities are awful.
I don't want to invest efforts into it, so just keep it as simple as possible.
Installation doesn't need at all, in fact...

**Closed by T-Troll** 2022-11-14 00:21 UTC
